version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8096:8096
    network_mode: "host"
    volumes:
      - /home/michael/jellyfin/config:/config
      - /home/michael/jellyfin/cache:/cache
      - /media/michael/Hebner's Hardrive/Movies:/media/Movies
      - /media/michael/Hebner's Hardrive/Shows:/media/TV
    restart: "unless-stopped"





